name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: ./packages/container # Set working directory to the container package

jobs: # Define the jobs for the workflow. we can run multiple jobs in parallel or sequentially.
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Check out the repository code

      - name: Install dependencies
        run: npm ci

      - name: Build container package
        run: npm run build

      - name: Configure AWS CLI
        uses: shinyinc/action-aws-cli@v1.2

      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
